[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirect is optional - it ensures that all routes will be handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 